### ISSUE TITLE
Segmentation Fault when doing anything using sshpass

### ISSUE THREAD

**Issue by sketch54** [kevinburke/sshpass#15]
When I use sshpass on my Raspberry Pi Zero 2w, I simply get the message "Segmentation Fault" when I run any sshpass command. Even just trying to run `sshpass` and nothing else. I installed it using the .deb download from [Debian Packages](https://packages.debian.org/sid/armhf/sshpass/download). Using sudo or specifying the file path to sshpass in `/usr/bin/sshpass` makes no difference either.

**Comment by kevinburke** [comment]
This repo is just a mirror of a project I used a decade ago at work. I
don’t maintain or investigate any issues or PR’s.

**Comment by sketch54** [comment]
Damn ok the bottom of the repo says you're a maintainer so I thought this was the repo.
