### ISSUE TITLE
Incomplete fork

### ISSUE THREAD

**Issue by owenstranathan** [kevinburke/sshpass#5]
This repo is missing "at least" a `README` which is read by autoconf to make the Makefile.

I ended up compiling from the sourceforge mirror, but this repo should probably be updated.

**Comment by kevinburke** [comment]
My guess is you just need to move the README.md back to README. Sorry I haven't used this tool in about five years.

**Comment by owenstranathan** [comment]
It's cool man. Just making this issue for posterity I guess. I looked more closely at the sourceforge mirror and it looks like the README there is just an empty file, so I guess anyone experiencing this problem can just `touch README` and move on with life. Closing.
